apiVersion: v1
kind: Service
metadata:
  name: geth-headless
  labels:
    app: geth
spec:
  clusterIP: None
  selector:
    app: geth
  ports:
    - port: 8545
      name: rpc-http
    - port: 8546
      name: rpc-ws
    - port: 30303
      name: p2p-tcp
    - port: 30303
      name: p2p-udp
      protocol: UDP